import {
  AE,
  AF,
  AL,
  AM,
  CW,
  AO,
  AR,
  AU,
  AW,
  AZ,
  BA,
  BB,
  BD,
  BG,
  BH,
  BI,
  BM,
  BN,
  BO,
  BR,
  BS,
  BT,
  BW,
  BY,
  BZ,
  CA,
  CD,
  CH,
  CL,
  CN,
  CO,
  CR,
  CU,
  CV,
  CZ,
  DJ,
  DK,
  DO,
  DZ,
  EG,
  ER,
  ET,
  EU,
  FJ,
  FK,
  GB,
  GE,
  GH,
  GI,
  GM,
  GN,
  GT,
  GY,
  HK,
  HN,
  HR,
  HT,
  HU,
  ID,
  IL,
  IN,
  IQ,
  IR,
  IS,
  JM,
  JO,
  JP,
  KE,
  KG,
  KH,
  KM,
  KP,
  KR,
  KW,
  KY,
  KZ,
  LA,
  LB,
  LK,
  LR,
  LS,
  LY,
  MA,
  MD,
  MG,
  MK,
  MM,
  MN,
  MO,
  MR,
  MU,
  MV,
  MW,
  MX,
  MY,
  MZ,
  NA,
  NG,
  NI,
  NO,
  NP,
  NZ,
  OM,
  PA,
  PE,
  PG,
  PH,
  PK,
  PL,
  PY,
  QA,
  RO,
  RS,
  RU,
  RW,
  SA,
  SB,
  SC,
  SD,
  SE,
  SG,
  SH,
  SL,
  SO,
  SR,
  SS,
  ST,
  SY,
  SZ,
  TH,
  TJ,
  TM,
  TN,
  TO,
  TR,
  TT,
  TW,
  TZ,
  UA,
  UG,
  US,
  UY,
  UZ,
  VE,
  VN,
  VU,
  WS,
  CM,
  AG,
  SN,
  PF,
  YE,
  ZA,
  ZM,
  ZW,
  FlagComponent,
} from "country-flag-icons/react/1x1";

export const currencyList: {
  value: string;
  label: string;
  details: {
    country: string;
    currencySymbol: string;
    currencyName: string;
    currencyShortForm: string;
    icon: FlagComponent;
    iconName: string;
  };
}[] = [
  {
    value: "AED",
    label: "AED",
    details: {
      country: "AE",
      currencySymbol: "AED",
      currencyName: "United Arab Emirates Dirham",
      currencyShortForm: "AED",
      icon: AE,
      iconName: "AE",
    },
  },
  {
    value: "AFN",
    label: "AFN",
    details: {
      country: "AF",
      currencySymbol: "AFN",
      currencyName: "Afghan Afghani",
      currencyShortForm: "AFN",
      icon: AF,
      iconName: "AF",
    },
  },
  {
    value: "ALL",
    label: "ALL",
    details: {
      country: "AL",
      currencySymbol: "ALL",
      currencyName: "Albanian Lek",
      currencyShortForm: "ALL",
      icon: AL,
      iconName: "AL",
    },
  },
  {
    value: "AMD",
    label: "AMD",
    details: {
      country: "AM",
      currencySymbol: "AMD",
      currencyName: "Armenian Dram",
      currencyShortForm: "AMD",
      icon: AM,
      iconName: "AM",
    },
  },
  {
    value: "ANG",
    label: "ANG",
    details: {
      country: "CW",
      currencySymbol: "ANG",
      currencyName: "Netherlands Antillean Guilder",
      currencyShortForm: "ANG",
      icon: CW,
      iconName: "CW",
    },
  },
  {
    value: "AOA",
    label: "AOA",
    details: {
      country: "AO",
      currencySymbol: "AOA",
      currencyName: "Angolan Kwanza",
      currencyShortForm: "AOA",
      icon: AO,
      iconName: "AO",
    },
  },
  {
    value: "ARS",
    label: "ARS",
    details: {
      country: "AR",
      currencySymbol: "ARS",
      currencyName: "Argentine Peso",
      currencyShortForm: "ARS",
      icon: AR,
      iconName: "AR",
    },
  },
  {
    value: "AUD",
    label: "AUD",
    details: {
      country: "AU",
      currencySymbol: "A$",
      currencyName: "Australian Dollar",
      currencyShortForm: "AUD",
      icon: AU,
      iconName: "AU",
    },
  },
  {
    value: "AWG",
    label: "AWG",
    details: {
      country: "AW",
      currencySymbol: "AWG",
      currencyName: "Aruban Florin",
      currencyShortForm: "AWG",
      icon: AW,
      iconName: "AW",
    },
  },
  {
    value: "AZN",
    label: "AZN",
    details: {
      country: "AZ",
      currencySymbol: "AZN",
      currencyName: "Azerbaijani Manat",
      currencyShortForm: "AZN",
      icon: AZ,
      iconName: "AZ",
    },
  },
  {
    value: "BAM",
    label: "BAM",
    details: {
      country: "BA",
      currencySymbol: "BAM",
      currencyName: "Bosnia-Herzegovina Convertible Mark",
      currencyShortForm: "BAM",
      icon: BA,
      iconName: "BA",
    },
  },
  {
    value: "BBD",
    label: "BBD",
    details: {
      country: "BB",
      currencySymbol: "BBD",
      currencyName: "Barbadian Dollar",
      currencyShortForm: "BBD",
      icon: BB,
      iconName: "BB",
    },
  },
  {
    value: "BDT",
    label: "BDT",
    details: {
      country: "BD",
      currencySymbol: "BDT",
      currencyName: "Bangladeshi Taka",
      currencyShortForm: "BDT",
      icon: BD,
      iconName: "BD",
    },
  },
  {
    value: "BGN",
    label: "BGN",
    details: {
      country: "BG",
      currencySymbol: "BGN",
      currencyName: "Bulgarian Lev",
      currencyShortForm: "BGN",
      icon: BG,
      iconName: "BG",
    },
  },
  {
    value: "BHD",
    label: "BHD",
    details: {
      country: "BH",
      currencySymbol: "BHD",
      currencyName: "Bahraini Dinar",
      currencyShortForm: "BHD",
      icon: BH,
      iconName: "BH",
    },
  },
  {
    value: "BIF",
    label: "BIF",
    details: {
      country: "BI",
      currencySymbol: "BIF",
      currencyName: "Burundian Franc",
      currencyShortForm: "BIF",
      icon: BI,
      iconName: "BI",
    },
  },
  {
    value: "BMD",
    label: "BMD",
    details: {
      country: "BM",
      currencySymbol: "BMD",
      currencyName: "Bermudan Dollar",
      currencyShortForm: "BMD",
      icon: BM,
      iconName: "BM",
    },
  },
  {
    value: "BND",
    label: "BND",
    details: {
      country: "BN",
      currencySymbol: "BND",
      currencyName: "Brunei Dollar",
      currencyShortForm: "BND",
      icon: BN,
      iconName: "BN",
    },
  },
  {
    value: "BOB",
    label: "BOB",
    details: {
      country: "BO",
      currencySymbol: "BOB",
      currencyName: "Bolivian Boliviano",
      currencyShortForm: "BOB",
      icon: BO,
      iconName: "BO",
    },
  },
  {
    value: "BRL",
    label: "BRL",
    details: {
      country: "BR",
      currencySymbol: "R$",
      currencyName: "Brazilian Real",
      currencyShortForm: "BRL",
      icon: BR,
      iconName: "BR",
    },
  },
  {
    value: "BSD",
    label: "BSD",
    details: {
      country: "BS",
      currencySymbol: "BSD",
      currencyName: "Bahamian Dollar",
      currencyShortForm: "BSD",
      icon: BS,
      iconName: "BS",
    },
  },
  {
    value: "BTN",
    label: "BTN",
    details: {
      country: "BT",
      currencySymbol: "BTN",
      currencyName: "Bhutanese Ngultrum",
      currencyShortForm: "BTN",
      icon: BT,
      iconName: "BT",
    },
  },
  {
    value: "BWP",
    label: "BWP",
    details: {
      country: "BW",
      currencySymbol: "BWP",
      currencyName: "Botswanan Pula",
      currencyShortForm: "BWP",
      icon: BW,
      iconName: "BW",
    },
  },
  {
    value: "BYN",
    label: "BYN",
    details: {
      country: "BY",
      currencySymbol: "BYN",
      currencyName: "Belarusian Ruble",
      currencyShortForm: "BYN",
      icon: BY,
      iconName: "BY",
    },
  },
  {
    value: "BZD",
    label: "BZD",
    details: {
      country: "BZ",
      currencySymbol: "BZD",
      currencyName: "Belize Dollar",
      currencyShortForm: "BZD",
      icon: BZ,
      iconName: "BZ",
    },
  },
  {
    value: "CAD",
    label: "CAD",
    details: {
      country: "CA",
      currencySymbol: "CA$",
      currencyName: "Canadian Dollar",
      currencyShortForm: "CAD",
      icon: CA,
      iconName: "CA",
    },
  },
  {
    value: "CDF",
    label: "CDF",
    details: {
      country: "CD",
      currencySymbol: "CDF",
      currencyName: "Congolese Franc",
      currencyShortForm: "CDF",
      icon: CD,
      iconName: "CD",
    },
  },
  {
    value: "CHF",
    label: "CHF",
    details: {
      country: "CH",
      currencySymbol: "CHF",
      currencyName: "Swiss Franc",
      currencyShortForm: "CHF",
      icon: CH,
      iconName: "CH",
    },
  },
  {
    value: "CLP",
    label: "CLP",
    details: {
      country: "CL",
      currencySymbol: "CLP",
      currencyName: "Chilean Peso",
      currencyShortForm: "CLP",
      icon: CL,
      iconName: "CL",
    },
  },
  {
    value: "CNY",
    label: "CNY",
    details: {
      country: "CN",
      currencySymbol: "CN¥",
      currencyName: "Chinese Yuan",
      currencyShortForm: "CNY",
      icon: CN,
      iconName: "CN",
    },
  },
  {
    value: "COP",
    label: "COP",
    details: {
      country: "CO",
      currencySymbol: "COP",
      currencyName: "Colombian Peso",
      currencyShortForm: "COP",
      icon: CO,
      iconName: "CO",
    },
  },
  {
    value: "CRC",
    label: "CRC",
    details: {
      country: "CR",
      currencySymbol: "CRC",
      currencyName: "Costa Rican Colón",
      currencyShortForm: "CRC",
      icon: CR,
      iconName: "CR",
    },
  },
  {
    value: "CUP",
    label: "CUP",
    details: {
      country: "CU",
      currencySymbol: "CUP",
      currencyName: "Cuban Peso",
      currencyShortForm: "CUP",
      icon: CU,
      iconName: "CU",
    },
  },
  {
    value: "CVE",
    label: "CVE",
    details: {
      country: "CV",
      currencySymbol: "CVE",
      currencyName: "Cape Verdean Escudo",
      currencyShortForm: "CVE",
      icon: CV,
      iconName: "CV",
    },
  },
  {
    value: "CZK",
    label: "CZK",
    details: {
      country: "CZ",
      currencySymbol: "CZK",
      currencyName: "Czech Koruna",
      currencyShortForm: "CZK",
      icon: CZ,
      iconName: "CZ",
    },
  },
  {
    value: "DJF",
    label: "DJF",
    details: {
      country: "DJ",
      currencySymbol: "DJF",
      currencyName: "Djiboutian Franc",
      currencyShortForm: "DJF",
      icon: DJ,
      iconName: "DJ",
    },
  },
  {
    value: "DKK",
    label: "DKK",
    details: {
      country: "DK",
      currencySymbol: "DKK",
      currencyName: "Danish Krone",
      currencyShortForm: "DKK",
      icon: DK,
      iconName: "DK",
    },
  },
  {
    value: "DOP",
    label: "DOP",
    details: {
      country: "DO",
      currencySymbol: "DOP",
      currencyName: "Dominican Peso",
      currencyShortForm: "DOP",
      icon: DO,
      iconName: "DO",
    },
  },
  {
    value: "DZD",
    label: "DZD",
    details: {
      country: "DZ",
      currencySymbol: "DZD",
      currencyName: "Algerian Dinar",
      currencyShortForm: "DZD",
      icon: DZ,
      iconName: "DZ",
    },
  },
  {
    value: "EGP",
    label: "EGP",
    details: {
      country: "EG",
      currencySymbol: "EGP",
      currencyName: "Egyptian Pound",
      currencyShortForm: "EGP",
      icon: EG,
      iconName: "EG",
    },
  },
  {
    value: "ERN",
    label: "ERN",
    details: {
      country: "ER",
      currencySymbol: "ERN",
      currencyName: "Eritrean Nakfa",
      currencyShortForm: "ERN",
      icon: ER,
      iconName: "ER",
    },
  },
  {
    value: "ETB",
    label: "ETB",
    details: {
      country: "ET",
      currencySymbol: "ETB",
      currencyName: "Ethiopian Birr",
      currencyShortForm: "ETB",
      icon: ET,
      iconName: "ET",
    },
  },
  {
    value: "EUR",
    label: "EUR",
    details: {
      country: "EU",
      currencySymbol: "€",
      currencyName: "Euro",
      currencyShortForm: "EUR",
      icon: EU,
      iconName: "EU",
    },
  },
  {
    value: "FJD",
    label: "FJD",
    details: {
      country: "FJ",
      currencySymbol: "FJD",
      currencyName: "Fijian Dollar",
      currencyShortForm: "FJD",
      icon: FJ,
      iconName: "FJ",
    },
  },
  {
    value: "FKP",
    label: "FKP",
    details: {
      country: "FK",
      currencySymbol: "FKP",
      currencyName: "Falkland Islands Pound",
      currencyShortForm: "FKP",
      icon: FK,
      iconName: "FK",
    },
  },
  {
    value: "GBP",
    label: "GBP",
    details: {
      country: "GB",
      currencySymbol: "£",
      currencyName: "British Pound",
      currencyShortForm: "GBP",
      icon: GB,
      iconName: "GB",
    },
  },
  {
    value: "GEL",
    label: "GEL",
    details: {
      country: "GE",
      currencySymbol: "GEL",
      currencyName: "Georgian Lari",
      currencyShortForm: "GEL",
      icon: GE,
      iconName: "GE",
    },
  },
  {
    value: "GHS",
    label: "GHS",
    details: {
      country: "GH",
      currencySymbol: "GHS",
      currencyName: "Ghanaian Cedi",
      currencyShortForm: "GHS",
      icon: GH,
      iconName: "GH",
    },
  },
  {
    value: "GIP",
    label: "GIP",
    details: {
      country: "GI",
      currencySymbol: "GIP",
      currencyName: "Gibraltar Pound",
      currencyShortForm: "GIP",
      icon: GI,
      iconName: "GI",
    },
  },
  {
    value: "GMD",
    label: "GMD",
    details: {
      country: "GM",
      currencySymbol: "GMD",
      currencyName: "Gambian Dalasi",
      currencyShortForm: "GMD",
      icon: GM,
      iconName: "GM",
    },
  },
  {
    value: "GNF",
    label: "GNF",
    details: {
      country: "GN",
      currencySymbol: "GNF",
      currencyName: "Guinean Franc",
      currencyShortForm: "GNF",
      icon: GN,
      iconName: "GN",
    },
  },
  {
    value: "GTQ",
    label: "GTQ",
    details: {
      country: "GT",
      currencySymbol: "GTQ",
      currencyName: "Guatemalan Quetzal",
      currencyShortForm: "GTQ",
      icon: GT,
      iconName: "GT",
    },
  },
  {
    value: "GYD",
    label: "GYD",
    details: {
      country: "GY",
      currencySymbol: "GYD",
      currencyName: "Guyanaese Dollar",
      currencyShortForm: "GYD",
      icon: GY,
      iconName: "GY",
    },
  },
  {
    value: "HKD",
    label: "HKD",
    details: {
      country: "HK",
      currencySymbol: "HK$",
      currencyName: "Hong Kong Dollar",
      currencyShortForm: "HKD",
      icon: HK,
      iconName: "HK",
    },
  },
  {
    value: "HNL",
    label: "HNL",
    details: {
      country: "HN",
      currencySymbol: "HNL",
      currencyName: "Honduran Lempira",
      currencyShortForm: "HNL",
      icon: HN,
      iconName: "HN",
    },
  },
  {
    value: "HRK",
    label: "HRK",
    details: {
      country: "HR",
      currencySymbol: "HRK",
      currencyName: "Croatian Kuna",
      currencyShortForm: "HRK",
      icon: HR,
      iconName: "HR",
    },
  },
  {
    value: "HTG",
    label: "HTG",
    details: {
      country: "HT",
      currencySymbol: "HTG",
      currencyName: "Haitian Gourde",
      currencyShortForm: "HTG",
      icon: HT,
      iconName: "HT",
    },
  },
  {
    value: "HUF",
    label: "HUF",
    details: {
      country: "HU",
      currencySymbol: "HUF",
      currencyName: "Hungarian Forint",
      currencyShortForm: "HUF",
      icon: HU,
      iconName: "HU",
    },
  },
  {
    value: "IDR",
    label: "IDR",
    details: {
      country: "ID",
      currencySymbol: "IDR",
      currencyName: "Indonesian Rupiah",
      currencyShortForm: "IDR",
      icon: ID,
      iconName: "ID",
    },
  },
  {
    value: "ILS",
    label: "ILS",
    details: {
      country: "IL",
      currencySymbol: "₪",
      currencyName: "Israeli New Shekel",
      currencyShortForm: "ILS",
      icon: IL,
      iconName: "IL",
    },
  },
  {
    value: "INR",
    label: "INR",
    details: {
      country: "IN",
      currencySymbol: "₹",
      currencyName: "Indian Rupee",
      currencyShortForm: "INR",
      icon: IN,
      iconName: "IN",
    },
  },
  {
    value: "IQD",
    label: "IQD",
    details: {
      country: "IQ",
      currencySymbol: "IQD",
      currencyName: "Iraqi Dinar",
      currencyShortForm: "IQD",
      icon: IQ,
      iconName: "IQ",
    },
  },
  {
    value: "IRR",
    label: "IRR",
    details: {
      country: "IR",
      currencySymbol: "IRR",
      currencyName: "Iranian Rial",
      currencyShortForm: "IRR",
      icon: IR,
      iconName: "IR",
    },
  },
  {
    value: "ISK",
    label: "ISK",
    details: {
      country: "IS",
      currencySymbol: "ISK",
      currencyName: "Icelandic Króna",
      currencyShortForm: "ISK",
      icon: IS,
      iconName: "IS",
    },
  },
  {
    value: "JMD",
    label: "JMD",
    details: {
      country: "JM",
      currencySymbol: "JMD",
      currencyName: "Jamaican Dollar",
      currencyShortForm: "JMD",
      icon: JM,
      iconName: "JM",
    },
  },
  {
    value: "JOD",
    label: "JOD",
    details: {
      country: "JO",
      currencySymbol: "JOD",
      currencyName: "Jordanian Dinar",
      currencyShortForm: "JOD",
      icon: JO,
      iconName: "JO",
    },
  },
  {
    value: "JPY",
    label: "JPY",
    details: {
      country: "JP",
      currencySymbol: "¥",
      currencyName: "Japanese Yen",
      currencyShortForm: "JPY",
      icon: JP,
      iconName: "JP",
    },
  },
  {
    value: "KES",
    label: "KES",
    details: {
      country: "KE",
      currencySymbol: "KES",
      currencyName: "Kenyan Shilling",
      currencyShortForm: "KES",
      icon: KE,
      iconName: "KE",
    },
  },
  {
    value: "KGS",
    label: "KGS",
    details: {
      country: "KG",
      currencySymbol: "KGS",
      currencyName: "Kyrgystani Som",
      currencyShortForm: "KGS",
      icon: KG,
      iconName: "KG",
    },
  },
  {
    value: "KHR",
    label: "KHR",
    details: {
      country: "KH",
      currencySymbol: "KHR",
      currencyName: "Cambodian Riel",
      currencyShortForm: "KHR",
      icon: KH,
      iconName: "KH",
    },
  },
  {
    value: "KMF",
    label: "KMF",
    details: {
      country: "KM",
      currencySymbol: "KMF",
      currencyName: "Comorian Franc",
      currencyShortForm: "KMF",
      icon: KM,
      iconName: "KM",
    },
  },
  {
    value: "KPW",
    label: "KPW",
    details: {
      country: "KP",
      currencySymbol: "KPW",
      currencyName: "North Korean Won",
      currencyShortForm: "KPW",
      icon: KP,
      iconName: "KP",
    },
  },
  {
    value: "KRW",
    label: "KRW",
    details: {
      country: "KR",
      currencySymbol: "₩",
      currencyName: "South Korean Won",
      currencyShortForm: "KRW",
      icon: KR,
      iconName: "KR",
    },
  },
  {
    value: "KWD",
    label: "KWD",
    details: {
      country: "KW",
      currencySymbol: "KWD",
      currencyName: "Kuwaiti Dinar",
      currencyShortForm: "KWD",
      icon: KW,
      iconName: "KW",
    },
  },
  {
    value: "KYD",
    label: "KYD",
    details: {
      country: "KY",
      currencySymbol: "KYD",
      currencyName: "Cayman Islands Dollar",
      currencyShortForm: "KYD",
      icon: KY,
      iconName: "KY",
    },
  },
  {
    value: "KZT",
    label: "KZT",
    details: {
      country: "KZ",
      currencySymbol: "KZT",
      currencyName: "Kazakhstani Tenge",
      currencyShortForm: "KZT",
      icon: KZ,
      iconName: "KZ",
    },
  },
  {
    value: "LAK",
    label: "LAK",
    details: {
      country: "LA",
      currencySymbol: "LAK",
      currencyName: "Laotian Kip",
      currencyShortForm: "LAK",
      icon: LA,
      iconName: "LA",
    },
  },
  {
    value: "LBP",
    label: "LBP",
    details: {
      country: "LB",
      currencySymbol: "LBP",
      currencyName: "Lebanese Pound",
      currencyShortForm: "LBP",
      icon: LB,
      iconName: "LB",
    },
  },
  {
    value: "LKR",
    label: "LKR",
    details: {
      country: "LK",
      currencySymbol: "LKR",
      currencyName: "Sri Lankan Rupee",
      currencyShortForm: "LKR",
      icon: LK,
      iconName: "LK",
    },
  },
  {
    value: "LRD",
    label: "LRD",
    details: {
      country: "LR",
      currencySymbol: "LRD",
      currencyName: "Liberian Dollar",
      currencyShortForm: "LRD",
      icon: LR,
      iconName: "LR",
    },
  },
  {
    value: "LSL",
    label: "LSL",
    details: {
      country: "LS",
      currencySymbol: "LSL",
      currencyName: "Lesotho Loti",
      currencyShortForm: "LSL",
      icon: LS,
      iconName: "LS",
    },
  },
  {
    value: "LYD",
    label: "LYD",
    details: {
      country: "LY",
      currencySymbol: "LYD",
      currencyName: "Libyan Dinar",
      currencyShortForm: "LYD",
      icon: LY,
      iconName: "LY",
    },
  },
  {
    value: "MAD",
    label: "MAD",
    details: {
      country: "MA",
      currencySymbol: "MAD",
      currencyName: "Moroccan Dirham",
      currencyShortForm: "MAD",
      icon: MA,
      iconName: "MA",
    },
  },
  {
    value: "MDL",
    label: "MDL",
    details: {
      country: "MD",
      currencySymbol: "MDL",
      currencyName: "Moldovan Leu",
      currencyShortForm: "MDL",
      icon: MD,
      iconName: "MD",
    },
  },
  {
    value: "MGA",
    label: "MGA",
    details: {
      country: "MG",
      currencySymbol: "MGA",
      currencyName: "Malagasy Ariary",
      currencyShortForm: "MGA",
      icon: MG,
      iconName: "MG",
    },
  },
  {
    value: "MKD",
    label: "MKD",
    details: {
      country: "MK",
      currencySymbol: "MKD",
      currencyName: "Macedonian Denar",
      currencyShortForm: "MKD",
      icon: MK,
      iconName: "MK",
    },
  },
  {
    value: "MMK",
    label: "MMK",
    details: {
      country: "MM",
      currencySymbol: "MMK",
      currencyName: "Myanmar Kyat",
      currencyShortForm: "MMK",
      icon: MM,
      iconName: "MM",
    },
  },
  {
    value: "MNT",
    label: "MNT",
    details: {
      country: "MN",
      currencySymbol: "MNT",
      currencyName: "Mongolian Tugrik",
      currencyShortForm: "MNT",
      icon: MN,
      iconName: "MN",
    },
  },
  {
    value: "MOP",
    label: "MOP",
    details: {
      country: "MO",
      currencySymbol: "MOP",
      currencyName: "Macanese Pataca",
      currencyShortForm: "MOP",
      icon: MO,
      iconName: "MO",
    },
  },
  {
    value: "MRU",
    label: "MRU",
    details: {
      country: "MR",
      currencySymbol: "MRU",
      currencyName: "Mauritanian Ouguiya",
      currencyShortForm: "MRU",
      icon: MR,
      iconName: "MR",
    },
  },
  {
    value: "MUR",
    label: "MUR",
    details: {
      country: "MU",
      currencySymbol: "MUR",
      currencyName: "Mauritian Rupee",
      currencyShortForm: "MUR",
      icon: MU,
      iconName: "MU",
    },
  },
  {
    value: "MVR",
    label: "MVR",
    details: {
      country: "MV",
      currencySymbol: "MVR",
      currencyName: "Maldivian Rufiyaa",
      currencyShortForm: "MVR",
      icon: MV,
      iconName: "MV",
    },
  },
  {
    value: "MWK",
    label: "MWK",
    details: {
      country: "MW",
      currencySymbol: "MWK",
      currencyName: "Malawian Kwacha",
      currencyShortForm: "MWK",
      icon: MW,
      iconName: "MW",
    },
  },
  {
    value: "MXN",
    label: "MXN",
    details: {
      country: "MX",
      currencySymbol: "MX$",
      currencyName: "Mexican Peso",
      currencyShortForm: "MXN",
      icon: MX,
      iconName: "MX",
    },
  },
  {
    value: "MYR",
    label: "MYR",
    details: {
      country: "MY",
      currencySymbol: "MYR",
      currencyName: "Malaysian Ringgit",
      currencyShortForm: "MYR",
      icon: MY,
      iconName: "MY",
    },
  },
  {
    value: "MZN",
    label: "MZN",
    details: {
      country: "MZ",
      currencySymbol: "MZN",
      currencyName: "Mozambican Metical",
      currencyShortForm: "MZN",
      icon: MZ,
      iconName: "MZ",
    },
  },
  {
    value: "NAD",
    label: "NAD",
    details: {
      country: "NA",
      currencySymbol: "NAD",
      currencyName: "Namibian Dollar",
      currencyShortForm: "NAD",
      icon: NA,
      iconName: "NA",
    },
  },
  {
    value: "NGN",
    label: "NGN",
    details: {
      country: "NG",
      currencySymbol: "NGN",
      currencyName: "Nigerian Naira",
      currencyShortForm: "NGN",
      icon: NG,
      iconName: "NG",
    },
  },
  {
    value: "NIO",
    label: "NIO",
    details: {
      country: "NI",
      currencySymbol: "NIO",
      currencyName: "Nicaraguan Córdoba",
      currencyShortForm: "NIO",
      icon: NI,
      iconName: "NI",
    },
  },
  {
    value: "NOK",
    label: "NOK",
    details: {
      country: "NO",
      currencySymbol: "NOK",
      currencyName: "Norwegian Krone",
      currencyShortForm: "NOK",
      icon: NO,
      iconName: "NO",
    },
  },
  {
    value: "NPR",
    label: "NPR",
    details: {
      country: "NP",
      currencySymbol: "NPR",
      currencyName: "Nepalese Rupee",
      currencyShortForm: "NPR",
      icon: NP,
      iconName: "NP",
    },
  },
  {
    value: "NZD",
    label: "NZD",
    details: {
      country: "NZ",
      currencySymbol: "NZ$",
      currencyName: "New Zealand Dollar",
      currencyShortForm: "NZD",
      icon: NZ,
      iconName: "NZ",
    },
  },
  {
    value: "OMR",
    label: "OMR",
    details: {
      country: "OM",
      currencySymbol: "OMR",
      currencyName: "Omani Rial",
      currencyShortForm: "OMR",
      icon: OM,
      iconName: "OM",
    },
  },
  {
    value: "PAB",
    label: "PAB",
    details: {
      country: "PA",
      currencySymbol: "PAB",
      currencyName: "Panamanian Balboa",
      currencyShortForm: "PAB",
      icon: PA,
      iconName: "PA",
    },
  },
  {
    value: "PEN",
    label: "PEN",
    details: {
      country: "PE",
      currencySymbol: "PEN",
      currencyName: "Peruvian Sol",
      currencyShortForm: "PEN",
      icon: PE,
      iconName: "PE",
    },
  },
  {
    value: "PGK",
    label: "PGK",
    details: {
      country: "PG",
      currencySymbol: "PGK",
      currencyName: "Papua New Guinean Kina",
      currencyShortForm: "PGK",
      icon: PG,
      iconName: "PG",
    },
  },
  {
    value: "PHP",
    label: "PHP",
    details: {
      country: "PH",
      currencySymbol: "₱",
      currencyName: "Philippine Peso",
      currencyShortForm: "PHP",
      icon: PH,
      iconName: "PH",
    },
  },
  {
    value: "PKR",
    label: "PKR",
    details: {
      country: "PK",
      currencySymbol: "PKR",
      currencyName: "Pakistani Rupee",
      currencyShortForm: "PKR",
      icon: PK,
      iconName: "PK",
    },
  },
  {
    value: "PLN",
    label: "PLN",
    details: {
      country: "PL",
      currencySymbol: "PLN",
      currencyName: "Polish Zloty",
      currencyShortForm: "PLN",
      icon: PL,
      iconName: "PL",
    },
  },
  {
    value: "PYG",
    label: "PYG",
    details: {
      country: "PY",
      currencySymbol: "PYG",
      currencyName: "Paraguayan Guarani",
      currencyShortForm: "PYG",
      icon: PY,
      iconName: "PY",
    },
  },
  {
    value: "QAR",
    label: "QAR",
    details: {
      country: "QA",
      currencySymbol: "QAR",
      currencyName: "Qatari Riyal",
      currencyShortForm: "QAR",
      icon: QA,
      iconName: "QA",
    },
  },
  {
    value: "RON",
    label: "RON",
    details: {
      country: "RO",
      currencySymbol: "RON",
      currencyName: "Romanian Leu",
      currencyShortForm: "RON",
      icon: RO,
      iconName: "RO",
    },
  },
  {
    value: "RSD",
    label: "RSD",
    details: {
      country: "RS",
      currencySymbol: "RSD",
      currencyName: "Serbian Dinar",
      currencyShortForm: "RSD",
      icon: RS,
      iconName: "RS",
    },
  },
  {
    value: "RUB",
    label: "RUB",
    details: {
      country: "RU",
      currencySymbol: "RUB",
      currencyName: "Russian Ruble",
      currencyShortForm: "RUB",
      icon: RU,
      iconName: "RU",
    },
  },
  {
    value: "RWF",
    label: "RWF",
    details: {
      country: "RW",
      currencySymbol: "RWF",
      currencyName: "Rwandan Franc",
      currencyShortForm: "RWF",
      icon: RW,
      iconName: "RW",
    },
  },
  {
    value: "SAR",
    label: "SAR",
    details: {
      country: "SA",
      currencySymbol: "SAR",
      currencyName: "Saudi Riyal",
      currencyShortForm: "SAR",
      icon: SA,
      iconName: "SA",
    },
  },
  {
    value: "SBD",
    label: "SBD",
    details: {
      country: "SB",
      currencySymbol: "SBD",
      currencyName: "Solomon Islands Dollar",
      currencyShortForm: "SBD",
      icon: SB,
      iconName: "SB",
    },
  },
  {
    value: "SCR",
    label: "SCR",
    details: {
      country: "SC",
      currencySymbol: "SCR",
      currencyName: "Seychellois Rupee",
      currencyShortForm: "SCR",
      icon: SC,
      iconName: "SC",
    },
  },
  {
    value: "SDG",
    label: "SDG",
    details: {
      country: "SD",
      currencySymbol: "SDG",
      currencyName: "Sudanese Pound",
      currencyShortForm: "SDG",
      icon: SD,
      iconName: "SD",
    },
  },
  {
    value: "SEK",
    label: "SEK",
    details: {
      country: "SE",
      currencySymbol: "SEK",
      currencyName: "Swedish Krona",
      currencyShortForm: "SEK",
      icon: SE,
      iconName: "SE",
    },
  },
  {
    value: "SGD",
    label: "SGD",
    details: {
      country: "SG",
      currencySymbol: "SGD",
      currencyName: "Singapore Dollar",
      currencyShortForm: "SGD",
      icon: SG,
      iconName: "SG",
    },
  },
  {
    value: "SHP",
    label: "SHP",
    details: {
      country: "SH",
      currencySymbol: "SHP",
      currencyName: "St. Helena Pound",
      currencyShortForm: "SHP",
      icon: SH,
      iconName: "SH",
    },
  },
  {
    value: "SLL",
    label: "SLL",
    details: {
      country: "SL",
      currencySymbol: "SLL",
      currencyName: "Sierra Leonean Leone (1964—2022)",
      currencyShortForm: "SLL",
      icon: SL,
      iconName: "SL",
    },
  },
  {
    value: "SOS",
    label: "SOS",
    details: {
      country: "SO",
      currencySymbol: "SOS",
      currencyName: "Somali Shilling",
      currencyShortForm: "SOS",
      icon: SO,
      iconName: "SO",
    },
  },
  {
    value: "SRD",
    label: "SRD",
    details: {
      country: "SR",
      currencySymbol: "SRD",
      currencyName: "Surinamese Dollar",
      currencyShortForm: "SRD",
      icon: SR,
      iconName: "SR",
    },
  },
  {
    value: "SSP",
    label: "SSP",
    details: {
      country: "SS",
      currencySymbol: "SSP",
      currencyName: "South Sudanese Pound",
      currencyShortForm: "SSP",
      icon: SS,
      iconName: "SS",
    },
  },
  {
    value: "STN",
    label: "STN",
    details: {
      country: "ST",
      currencySymbol: "STN",
      currencyName: "São Tomé & Príncipe Dobra",
      currencyShortForm: "STN",
      icon: ST,
      iconName: "ST",
    },
  },
  {
    value: "SYP",
    label: "SYP",
    details: {
      country: "SY",
      currencySymbol: "SYP",
      currencyName: "Syrian Pound",
      currencyShortForm: "SYP",
      icon: SY,
      iconName: "SY",
    },
  },
  {
    value: "SZL",
    label: "SZL",
    details: {
      country: "SZ",
      currencySymbol: "SZL",
      currencyName: "Swazi Lilangeni",
      currencyShortForm: "SZL",
      icon: SZ,
      iconName: "SZ",
    },
  },
  {
    value: "THB",
    label: "THB",
    details: {
      country: "TH",
      currencySymbol: "THB",
      currencyName: "Thai Baht",
      currencyShortForm: "THB",
      icon: TH,
      iconName: "TH",
    },
  },
  {
    value: "TJS",
    label: "TJS",
    details: {
      country: "TJ",
      currencySymbol: "TJS",
      currencyName: "Tajikistani Somoni",
      currencyShortForm: "TJS",
      icon: TJ,
      iconName: "TJ",
    },
  },
  {
    value: "TMT",
    label: "TMT",
    details: {
      country: "TM",
      currencySymbol: "TMT",
      currencyName: "Turkmenistani Manat",
      currencyShortForm: "TMT",
      icon: TM,
      iconName: "TM",
    },
  },
  {
    value: "TND",
    label: "TND",
    details: {
      country: "TN",
      currencySymbol: "TND",
      currencyName: "Tunisian Dinar",
      currencyShortForm: "TND",
      icon: TN,
      iconName: "TN",
    },
  },
  {
    value: "TOP",
    label: "TOP",
    details: {
      country: "TO",
      currencySymbol: "TOP",
      currencyName: "Tongan Paʻanga",
      currencyShortForm: "TOP",
      icon: TO,
      iconName: "TO",
    },
  },
  {
    value: "TRY",
    label: "TRY",
    details: {
      country: "TR",
      currencySymbol: "TRY",
      currencyName: "Turkish Lira",
      currencyShortForm: "TRY",
      icon: TR,
      iconName: "TR",
    },
  },
  {
    value: "TTD",
    label: "TTD",
    details: {
      country: "TT",
      currencySymbol: "TTD",
      currencyName: "Trinidad & Tobago Dollar",
      currencyShortForm: "TTD",
      icon: TT,
      iconName: "TT",
    },
  },
  {
    value: "TWD",
    label: "TWD",
    details: {
      country: "TW",
      currencySymbol: "NT$",
      currencyName: "New Taiwan Dollar",
      currencyShortForm: "TWD",
      icon: TW,
      iconName: "TW",
    },
  },
  {
    value: "TZS",
    label: "TZS",
    details: {
      country: "TZ",
      currencySymbol: "TZS",
      currencyName: "Tanzanian Shilling",
      currencyShortForm: "TZS",
      icon: TZ,
      iconName: "TZ",
    },
  },
  {
    value: "UAH",
    label: "UAH",
    details: {
      country: "UA",
      currencySymbol: "UAH",
      currencyName: "Ukrainian Hryvnia",
      currencyShortForm: "UAH",
      icon: UA,
      iconName: "UA",
    },
  },
  {
    value: "UGX",
    label: "UGX",
    details: {
      country: "UG",
      currencySymbol: "UGX",
      currencyName: "Ugandan Shilling",
      currencyShortForm: "UGX",
      icon: UG,
      iconName: "UG",
    },
  },
  {
    value: "USD",
    label: "USD",
    details: {
      country: "US",
      currencySymbol: "$",
      currencyName: "US Dollar",
      currencyShortForm: "USD",
      icon: US,
      iconName: "US",
    },
  },
  {
    value: "UYU",
    label: "UYU",
    details: {
      country: "UY",
      currencySymbol: "UYU",
      currencyName: "Uruguayan Peso",
      currencyShortForm: "UYU",
      icon: UY,
      iconName: "UY",
    },
  },
  {
    value: "UZS",
    label: "UZS",
    details: {
      country: "UZ",
      currencySymbol: "UZS",
      currencyName: "Uzbekistani Som",
      currencyShortForm: "UZS",
      icon: UZ,
      iconName: "UZ",
    },
  },
  {
    value: "VES",
    label: "VES",
    details: {
      country: "VE",
      currencySymbol: "VES",
      currencyName: "Venezuelan Bolívar",
      currencyShortForm: "VES",
      icon: VE,
      iconName: "VE",
    },
  },
  {
    value: "VND",
    label: "VND",
    details: {
      country: "VN",
      currencySymbol: "₫",
      currencyName: "Vietnamese Dong",
      currencyShortForm: "VND",
      icon: VN,
      iconName: "VN",
    },
  },
  {
    value: "VUV",
    label: "VUV",
    details: {
      country: "VU",
      currencySymbol: "VUV",
      currencyName: "Vanuatu Vatu",
      currencyShortForm: "VUV",
      icon: VU,
      iconName: "VU",
    },
  },
  {
    value: "WST",
    label: "WST",
    details: {
      country: "WS",
      currencySymbol: "WST",
      currencyName: "Samoan Tala",
      currencyShortForm: "WST",
      icon: WS,
      iconName: "WS",
    },
  },
  {
    value: "XAF",
    label: "XAF",
    details: {
      country: "CM",
      currencySymbol: "FCFA",
      currencyName: "Central African CFA Franc",
      currencyShortForm: "XAF",
      icon: CM,
      iconName: "CM",
    },
  },
  {
    value: "XCD",
    label: "XCD",
    details: {
      country: "AG",
      currencySymbol: "EC$",
      currencyName: "East Caribbean Dollar",
      currencyShortForm: "XCD",
      icon: AG,
      iconName: "AG",
    },
  },
  {
    value: "XOF",
    label: "XOF",
    details: {
      country: "SN",
      currencySymbol: "F CFA",
      currencyName: "West African CFA Franc",
      currencyShortForm: "XOF",
      icon: SN,
      iconName: "SN",
    },
  },
  {
    value: "XPF",
    label: "XPF",
    details: {
      country: "PF",
      currencySymbol: "CFPF",
      currencyName: "CFP Franc",
      currencyShortForm: "XPF",
      icon: PF,
      iconName: "PF",
    },
  },
  {
    value: "YER",
    label: "YER",
    details: {
      country: "YE",
      currencySymbol: "YER",
      currencyName: "Yemeni Rial",
      currencyShortForm: "YER",
      icon: YE,
      iconName: "YE",
    },
  },
  {
    value: "ZAR",
    label: "ZAR",
    details: {
      country: "ZA",
      currencySymbol: "ZAR",
      currencyName: "South African Rand",
      currencyShortForm: "ZAR",
      icon: ZA,
      iconName: "ZA",
    },
  },
  {
    value: "ZMW",
    label: "ZMW",
    details: {
      country: "ZM",
      currencySymbol: "ZMW",
      currencyName: "Zambian Kwacha",
      currencyShortForm: "ZMW",
      icon: ZM,
      iconName: "ZM",
    },
  },
  {
    value: "ZWL",
    label: "ZWL",
    details: {
      country: "ZW",
      currencySymbol: "ZWL",
      currencyName: "Zimbabwean Dollar (2009)",
      currencyShortForm: "ZWL",
      icon: ZW,
      iconName: "ZW",
    },
  }
];
